config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

# Model for comment
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/models/post.rb
# frozen_string_literal: true

# Model for post
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  # dependent: :destroy will destroy all comments related
  # to the specific post if the post gets deleted as well

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Controller for comments
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    if @comment.save
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post), flash: { error: @comment.errors.full_messages }
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Controller for pages
class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controller for posts
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class="card">
    <div class="card-body">
      <p class="card-text">
        <strong><%= comment.username %></strong>: <%= comment.body %><br><br>
        <%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    </div>
  </div>
<% end %>
<hr>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <% flash.each do |type, msg| %>
    <% msg.each do |m| %>
      <div class="alert alert-danger"><%= m %></div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field(:username, { :class => 'form-control' }) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, { :class => 'form-control', :rows => '10' }) %>
  </p>

  <p>
    <%= f.submit({ :class => 'btn btn-primary' }) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Rails Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Simple Rails Blog</a>
        </div>

        <div class="navbar-collapse collpase">
          <ul class="nav navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Home", home_path, { :class => 'btn btn-secondary' } %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path, { :class => 'btn btn-success' } %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container pt-4 pb-5 mb-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field(:title, { :class => 'form-control' }) %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area(:body, { :class => 'form-control', :rows => '10' }) %>
  </p>

  <p>
    <%= f.submit({ :class => 'btn btn-primary' }) %>
    <%= link_to 'Cancel', post_path(@post), :class => 'btn btn-secondary' %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<div class="row">
<% if @posts.length() == 0 %>
  <div class="col-sm-4 mb-3">
    <div class="card">
      <div class="card-body">
          <p class="card-text text-truncate">There are no posts</p>

          <%= link_to "Create Post", new_post_path %>
      </div>
    </div>
  </div>
<% else %>
  <% @posts.each do |post| %>
    <div class="col-sm-4 mb-3">
      <div class="card">
        <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted">Author</h6>
            <p class="card-text text-truncate"><%= post.body %></p>

            <%= link_to "Read More", post_path(post), :class => 'card-link' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field(:title, { :class => 'form-control' }) %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area(:body, { :class => 'form-control', :rows => '10' }) %>
  </p>

  <p>
    <%= f.submit({ :class => 'btn btn-primary' }) %>
    <%= link_to 'Cancel', posts_path, :class => 'btn btn-secondary' %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<span class="tag is-rounded"><%= @post.comments.count %> comments</span>
<br><br>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>